const API_BASE=window.SF6_API_BASE||'https://sf6-live-researcher.u-ambers.workers.dev';
const CHARACTER_ROSTER=[['リュウ','ryu'],['ルーク','luke'],['ジェイミー','jamie'],['春麗','chunli'],['ガイル','guile'],['キンバリー','kimberly'],['ジュリ','juri'],['ケン','ken'],['ブランカ','blanka'],['ダルシム','dhalsim'],['エドモンド本田','honda'],['ザンギエフ','zangief'],['キャミィ','cammy'],['マノン','manon'],['マリーザ','marisa'],['リリー','lily'],['JP','jp'],['ディージェイ','deejay'],['ラシード','rashid'],['A.K.I.','aki'],['ED','ed'],['豪鬼','gouki'],['テリー','terry'],['舞','mai'],['ベガ','vega'],['エレナ','elena'],['サガット','sagat'],['C.ヴァイパー','cviper'],['アレックス','alex'],['イングリッド','ingrid'],['ヤスミン','yasmine']].map(([name,slug])=>({name,id:slug,image:`./assets/characters/character_${slug}_l.png`}));
const LIVE_CATEGORY_LABELS={ranked:'ランクマッチ',custom:'参加型',tournament:'大会',casual:'カジュアル',training:'トレーニング',avatar_battle:'アバターバトル',other:'その他'};
const STREAMER_CATEGORY_LABELS={pro_gamer:'プロゲーマー',vtuber:'VTuber',game_streamer:'ゲーム配信者'};
const state={data:{characters:CHARACTER_ROSTER,streams:[],upcoming:[],streamers:[]},view:'home',query:'',charFilter:'all',liveCategoryFilter:'all',favorites:JSON.parse(localStorage.getItem('sf6-live-favorites')||'[]'),streamerPage:1,streamerPageSize:200,streamerTotal:0,streamerHasNextPage:false,streamerPages:{}};
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>\\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;'}[c]));
const chars=()=>state.data.characters;const streams=()=>state.data.streams;const charByName=n=>chars().find(c=>c.name===n)||null;const characterSlug=n=>charByName(n)?.id||String(n||'').trim().normalize('NFKC').toLowerCase().replace(/[^\\p{L}\\p{N}]+/gu,'-');
const parseCharacterNames=v=>{const values=Array.isArray(v)?v:String(v??'').split(',');return [...new Set(values.map(x=>String(x??'').trim()).filter(x=>x&&x.toLowerCase()!=='unknown'))];};
const liveCategoryLabel=v=>LIVE_CATEGORY_LABELS[v]||v||'その他';const streamerCategoryLabel=v=>STREAMER_CATEGORY_LABELS[v]||v||'--';const isFav=id=>state.favorites.includes(id);const saveFavs=()=>localStorage.setItem('sf6-live-favorites',JSON.stringify(state.favorites));
function toggleFav(id){state.favorites=isFav(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];saveFavs();render();}
function nav(view){state.view=view;state.charFilter='all';state.liveCategoryFilter='all';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));render();}
function formatJst(value,fallback='--'){const d=new Date(value);if(Number.isNaN(d.getTime()))return fallback;return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(d);}
function filteredUpcoming(){return state.data.upcoming.filter(s=>(state.charFilter==='all'||s.characterNames.some(n=>characterSlug(n)===state.charFilter))&&(!state.query||`${s.streamer} ${s.title} ${s.characterNames.join(' ')}`.toLowerCase().includes(state.query.toLowerCase()))).sort((a,b)=>{const at=Date.parse(a.scheduledStart),bt=Date.parse(b.scheduledStart);if(!Number.isFinite(at)&&!Number.isFinite(bt))return 0;if(!Number.isFinite(at))return 1;if(!Number.isFinite(bt))return -1;return at-bt;});}
function filteredLive(){return streams().filter(s=>s.status==='live'&&(state.charFilter==='all'||s.characterNames.some(n=>characterSlug(n)===state.charFilter))&&(state.liveCategoryFilter==='all'||s.category===state.liveCategoryFilter)&&(!state.query||`${s.streamer} ${s.title} ${s.characterNames.join(' ')}`.toLowerCase().includes(state.query.toLowerCase())));}
function availableLiveCategories(){const order=['ranked','custom','tournament','casual','training','avatar_battle','other'];return [...new Set(streams().filter(s=>s.status==='live').map(s=>s.category||'other'))].sort((a,b)=>(order.indexOf(a)<0?999:order.indexOf(a))-(order.indexOf(b)<0?999:order.indexOf(b)));}
function liveCard(s){const names=s.characterNames.join(' / ');return `<article class="stream-card" data-open="${esc(s.id)}"><div class="thumb" style="background-image:url('${esc(s.thumbnail)}');background-size:cover;background-position:center"><span class="live-pill">● LIVE</span>${names?`<span class="char-badge">${esc(names)}</span>`:''}</div><div class="card-body"><div class="title-row"><strong class="stream-title">${esc(s.title)}</strong><button class="favorite ${isFav(s.streamerId)?'on':''}" data-fav="${esc(s.streamerId)}" aria-label="お気に入り">${isFav(s.streamerId)?'♥':'♡'}</button></div><div class="stream-channel">${esc(s.streamer)}</div><div class="meta">${names?`<span>◉ ${esc(names)}</span>`:''}<span class="live-category">${esc(liveCategoryLabel(s.category))}</span>${s.viewers!=null?`<span>👁 ${Number(s.viewers).toLocaleString()}</span>`:''}</div></div></article>`;}
function upcomingCard(s){const names=s.characterNames.join(' / ');return `<article class="upcoming-card" data-open="${esc(s.id)}"><div class="upcoming-thumb" style="background-image:${s.thumbnail?`linear-gradient(135deg,rgba(20,24,31,.12),rgba(17,21,27,.78)),url('${esc(s.thumbnail)}')`:'linear-gradient(135deg,#252b35,#11151b)'};background-size:cover;background-position:center"><span class="upcoming-time">${esc(formatJst(s.scheduledStart))}</span></div><div class="upcoming-body"><div class="title-row"><strong class="stream-title">${esc(s.title)}</strong><button class="favorite ${isFav(s.streamerId)?'on':''}" data-fav="${esc(s.streamerId)}" aria-label="お気に入り">${isFav(s.streamerId)?'♥':'♡'}</button></div><div class="stream-channel">${esc(s.streamer)}</div><div class="meta">${names?`<span>◉ ${esc(names)}</span>`:''}<span>YouTube</span></div></div></article>`;}
function home(){const live=filteredLive(),selectedCharacter=state.charFilter!=='all'?charByName(state.charFilter):null,selectedCategory=state.liveCategoryFilter!=='all'?liveCategoryLabel(state.liveCategoryFilter):null,categories=availableLiveCategories();return `<section class="section"><div class="section-head"><div><h2>🔴 NOW LIVE</h2><p>${selectedCharacter?`${esc(selectedCharacter.name)} の現在LIVE中の配信`:selectedCategory?`${esc(selectedCategory)} の現在LIVE中の配信`:'いま見られるスト6配信'}</p></div><span class="result-count">${live.length} streams</span></div><div class="filter-row"><button class="chip ${state.liveCategoryFilter==='all'?'active':''}" data-live-category="all">すべて</button>${categories.map(c=>`<button class="chip ${state.liveCategoryFilter===c?'active':''}" data-live-category="${esc(c)}">${esc(liveCategoryLabel(c))}</button>`).join('')}${selectedCharacter?`<button class="chip active" data-clear-char>◉ ${esc(selectedCharacter.name)}</button>`:''}</div><div class="live-grid">${live.length?live.map(liveCard).join(''):'<div class="empty">現在LIVE中の配信はありません。</div>'}</div></section>`;}
function upcomingPage(){const items=filteredUpcoming();return `<section class="section"><div class="section-head"><div><h2>配信予定</h2><p>YouTubeで公開予定になっているSF6 LIVE</p></div><span class="result-count">${items.length} streams</span></div><div class="filter-row"><button class="chip ${state.charFilter==='all'?'active':''}" data-upcoming-char="all">すべて</button>${chars().map(c=>`<button class="chip ${state.charFilter===c.id?'active':''}" data-upcoming-char="${c.id}">${esc(c.name)}</button>`).join('')}</div><div class="upcoming-grid">${items.length?items.map(upcomingCard).join(''):'<div class="empty">該当する配信予定はありません。</div>'}</div></section>`;}
function streamersPage(){const items=state.data.streamers||[],liveByChannel=new Map(streams().filter(s=>s.status==='live').map(s=>[s.streamerId,s])),page=state.streamerPage,total=state.streamerTotal||items.length,totalPages=Math.max(1,Math.ceil(total/state.streamerPageSize));const pageButtons=Array.from({length:totalPages},(_,i)=>i+1).filter(n=>n===1||n===totalPages||Math.abs(n-page)<=1);let last=0;const pager=pageButtons.map(n=>{const gap=last&&n-last>1?'<span class="pagination-gap">…</span>':'';last=n;return `${gap}<button class="pagination-button ${n===page?'active':''}" data-streamer-page="${n}">${n}</button>`}).join('');return `<section class="section"><div class="section-head"><div><h2>配信者</h2><p>Cloudflare D1に登録されている配信者情報</p></div><span class="result-count">${total} streamers</span></div><div class="streamer-grid">${items.map(x=>{const live=liveByChannel.get(x.id);const targetUrl=live?.youtubeUrl||x.channelUrl;return `<article class="streamer-card ${live?'is-live':''}" data-streamer-channel="${esc(x.id)}" data-streamer-url="${esc(targetUrl)}"><div class="channel-avatar-wrap">${x.channelThumbnailUrl?`<img class="channel-icon" src="${esc(x.channelThumbnailUrl)}" alt="${esc(x.name)} のYouTubeチャンネルアイコン" loading="lazy" referrerpolicy="no-referrer">`:''}${live?'<span class="live-pill">● LIVE</span>':''}</div><div class="streamer-row"><strong>${esc(x.name)}</strong><button class="favorite ${isFav(x.id)?'on':''}" data-fav="${esc(x.id)}">${isFav(x.id)?'♥':'♡'}</button></div><div class="streamer-stats"><span><b>登録者</b>${x.subscriberCount!=null?Number(x.subscriberCount).toLocaleString():'--'}</span><span><b>カテゴリ</b>${esc(x.streamerCategoryLabel||x.streamerCategory||'--')}</span></div><small>${x.lp!=null?`LP ${esc(x.lp)}`:''}${x.mr!=null?` · MR ${esc(x.mr)}`:''}</small></article>`;}).join('')}</div>${totalPages>1?`<div class="pagination" aria-label="配信者ページ"><button class="pagination-button" data-streamer-page="${page-1}" ${page<=1?'disabled':''}>‹</button>${pager}<button class="pagination-button" data-streamer-page="${page+1}" ${page>=totalPages?'disabled':''}>›</button></div>`:''}</section>`;}
function charactersPage(){return `<section class="section"><div class="section-head"><div><h2>キャラクター</h2><p>現在実装されているファイターの公式アート</p></div></div><div class="character-grid">${chars().map(c=>{const count=[...streams(),...state.data.upcoming].filter(s=>s.characterNames.some(n=>characterSlug(n)===c.id)).length;return `<article class="character-card" data-character="${c.id}"><div class="character-art image-art" style="background-image:linear-gradient(180deg,rgba(8,10,15,.02),rgba(8,10,15,.84)),url('${c.image}')"></div><strong>${esc(c.name)}</strong><small>${count} streams</small></article>`}).join('')}</div></section>`;}
function favoritesPage(){const fav=[...streams(),...state.data.upcoming].filter(s=>isFav(s.streamerId));return `<section class="section"><div class="section-head"><div><h2>お気に入り</h2><p>このブラウザだけに保存されます。アカウントは不要です。</p></div></div>${fav.length?`<div class="upcoming-grid">${fav.map(s=>s.status==='upcoming'?upcomingCard(s):liveCard(s)).join('')}</div>`:'<div class="empty">お気に入りの配信者はありません。</div>'}</section>`;}
function simplePage(title,body){return `<section class="section"><div class="page-card"><h2>${title}</h2>${body}</div></section>`;}
function noticePage(){return simplePage('お知らせ',`<div class="notice"><strong>2026/09/03</strong><br>サイトを更新しました。<span>配信中ページの表示を整理し、配信カテゴリによる絞り込みに対応しました。</span></div><div class="notice"><strong>2026/09/02</strong><br>配信者情報の更新機能を強化しました。<span>チャンネル情報を定期的に更新し、より新しい情報を表示できるようにしています。</span></div><div class="notice"><strong>2026/09/01</strong><br>SF6 LIVE RESEARCHERを公開しました。<span>Street Fighter 6の配信を探しやすくするためのストリームハブです。</span></div>`);}
function settingsPage(){return simplePage('設定',`<p>設定機能は現在準備中です。</p><p>今後、表示やお気に入りなどに関する設定機能を追加する予定です。</p>`);}
function helpPage(){return simplePage('使い方',`<div class="notice"><strong>SF6 LIVE RESEARCHERとは？</strong><span>Street Fighter 6の配信を探すためのサイトです。現在配信中の配信、配信予定、配信者をキャラクターやカテゴリから探すことができます。</span></div><div class="notice"><strong>配信中</strong><span>現在YouTubeで配信中のSF6配信を表示します。キャラクターや配信カテゴリを使って、見たい配信を絞り込めます。配信カードをクリックするとYouTubeの配信ページを開きます。</span></div><div class="notice"><strong>配信予定</strong><span>これから始まるSF6配信を確認できます。配信開始前の予定を探したい場合に利用してください。キャラクターから絞り込むこともできます。</span></div><div class="notice"><strong>配信者</strong><span>SF6を配信している配信者を一覧から探せます。登録者数や名前などの情報を確認でき、配信中の配信者にはLIVE表示が付きます。</span></div><div class="notice"><strong>キャラクター</strong><span>キャラクターを選択すると、そのキャラクターに関連する配信を探せます。「このキャラクターを使っている配信を見たい」という場合に便利です。</span></div><div class="notice"><strong>お気に入り</strong><span>気になる配信者をお気に入り登録すると、お気に入りページから確認できます。配信していないときでもお気に入りの配信者を確認できます。お気に入り情報はこのブラウザに保存され、ログインは必要ありません。</span></div><div class="notice"><strong>検索</strong><span>画面上部の検索欄から、配信者名や配信タイトル、キャラクターなどを検索できます。</span></div><div class="notice"><strong>データについて</strong><span>このサイトではYouTube上の公開情報を利用しています。自動収集した情報を表示しているため、実際のYouTube上の状態とタイムラグが発生する場合があります。</span></div>`);}
function render(){const app=$('#app'),titles={home:'配信中',upcoming:'配信予定',streamers:'配信者',characters:'キャラクター',favorites:'お気に入り',notice:'お知らせ',settings:'設定',help:'使い方'};$('#page-title').textContent=titles[state.view];if(state.view==='home')app.innerHTML=home();else if(state.view==='upcoming')app.innerHTML=upcomingPage();else if(state.view==='streamers')app.innerHTML=streamersPage();else if(state.view==='characters')app.innerHTML=charactersPage();else if(state.view==='favorites')app.innerHTML=favoritesPage();else if(state.view==='notice')app.innerHTML=noticePage();else if(state.view==='settings')app.innerHTML=settingsPage();else app.innerHTML=helpPage();bind();}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));document.querySelectorAll('[data-live-category]').forEach(b=>b.onclick=()=>{state.liveCategoryFilter=b.dataset.liveCategory;render();});document.querySelectorAll('[data-clear-live-filter]').forEach(b=>b.onclick=()=>{state.charFilter='all';state.liveCategoryFilter='all';state.view='home';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view==='home'));render();});document.querySelectorAll('[data-upcoming-char]').forEach(b=>b.onclick=()=>{state.charFilter=b.dataset.upcomingChar;state.liveCategoryFilter='all';state.view='upcoming';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view==='upcoming'));render();});document.querySelectorAll('[data-clear-char]').forEach(b=>b.onclick=()=>{state.charFilter='all';render();});document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav);});document.querySelectorAll('[data-open]').forEach(card=>card.onclick=()=>openStream(card.dataset.open));document.querySelectorAll('[data-streamer-page]').forEach(b=>b.onclick=()=>{if(!b.disabled)changeStreamerPage(Number(b.dataset.streamerPage));});document.querySelectorAll('[data-streamer-channel]').forEach(card=>card.onclick=e=>{if(e.target.closest('[data-fav]'))return;const url=card.dataset.streamerUrl;if(url)window.open(url,'_blank','noopener');});document.querySelectorAll('.character-card').forEach(card=>card.onclick=()=>{state.charFilter=card.dataset.character;state.liveCategoryFilter='all';state.view='home';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view==='home'));render();});}
function openStream(id){const s=[...streams(),...state.data.upcoming].find(x=>x.id===id);if(s)window.open(s.youtubeUrl,'_blank','noopener');}
function mapVideo(v){const characterNames=parseCharacterNames(v.main_characters??v.main_character);return {id:v.video_id,streamerId:v.channel_id,characterNames,streamer:v.sf6_player_name||v.channel_title||v.channel_id,channelThumbnailUrl:v.channel_thumbnail_url||'',status:v.status,viewers:v.concurrent_viewers,title:v.title||'',youtubeUrl:`https://www.youtube.com/watch?v=${v.video_id}`,thumbnail:v.thumbnail_url||`https://i.ytimg.com/vi/${v.video_id}/hqdefault.jpg`,lp:v.lp,mr:v.mr,category:v.category||'other',scheduledStart:v.scheduled_start_time,actualStart:v.actual_start_time,actualEnd:v.actual_end_time};}
function mapStreamer(s){return {id:s.channel_id,name:s.sf6_player_name||s.channel_title||s.channel_id,channelThumbnailUrl:s.channel_thumbnail_url||'',channelUrl:`https://www.youtube.com/channel/${encodeURIComponent(s.channel_id)}`,subscriberCount:s.subscriber_count,lp:s.lp,mr:s.mr,streamerCategory:s.streamer_category,streamerCategoryLabel:streamerCategoryLabel(s.streamer_category)};}
async function fetchJson(url){const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
async function fetchVideos(status,limit=200){return fetchJson(`${API_BASE}/api/videos?status=${encodeURIComponent(status)}&limit=${limit}`);}
async function fetchStreamers(page=1){const offset=(page-1)*state.streamerPageSize;if(state.streamerPages[offset]){const cached=state.streamerPages[offset];state.data.streamers=cached.items;state.streamerPage=page;state.streamerTotal=cached.total;state.streamerHasNextPage=cached.hasNextPage;return;}try{const payload=await fetchJson(`${API_BASE}/api/streamers?limit=${state.streamerPageSize}&offset=${offset}&sort=subscribers_desc`);const items=(payload.items||[]).map(mapStreamer);state.streamerPages[offset]={items,total:Number(payload.total||0),hasNextPage:Boolean(payload.hasNextPage)};state.data.streamers=items;state.streamerPage=page;state.streamerTotal=Number(payload.total||0);state.streamerHasNextPage=Boolean(payload.hasNextPage);}catch(e){console.error('streamers fetch failed',e);state.data.streamers=[];state.streamerTotal=0;state.streamerHasNextPage=false;}}
async function changeStreamerPage(page){const totalPages=Math.max(1,Math.ceil((state.streamerTotal||0)/state.streamerPageSize));if(page<1||page>totalPages||page===state.streamerPage)return;await fetchStreamers(page);render();}
async function loadApiData(){const [livePayload,upcomingPayload]=await Promise.all([fetchVideos('live'),fetchVideos('upcoming')]);await fetchStreamers(1);state.data.streams=(livePayload.items||[]).map(mapVideo).filter(v=>v.status==='live');state.data.upcoming=(upcomingPayload.items||[]).map(mapVideo).filter(v=>v.status==='upcoming');}
document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>nav(n.dataset.view));
const search=$('#search-input');if(search)search.oninput=()=>{state.query=search.value;render();};
loadApiData().then(render).catch(e=>{console.error(e);render();});
