const API_BASE=window.SF6_API_BASE||'https://sf6-live-researcher.u-ambers.workers.dev';
const CHARACTER_ROSTER=[['リュウ','ryu'],['ルーク','luke'],['ジェイミー','jamie'],['春麗','chunli'],['ガイル','guile'],['キンバリー','kimberly'],['ジュリ','juri'],['ケン','ken'],['ブランカ','blanka'],['ダルシム','dhalsim'],['エドモンド本田','honda'],['ザンギエフ','zangief'],['キャミィ','cammy'],['マノン','manon'],['マリーザ','marisa'],['リリー','lily'],['JP','jp'],['ディージェイ','deejay'],['ラシード','rashid'],['A.K.I.','aki'],['ED','ed'],['豪鬼','gouki'],['テリー','terry'],['舞','mai'],['ベガ','vega'],['エレナ','elena'],['サガット','sagat'],['C.ヴァイパー','cviper'],['アレックス','alex'],['イングリッド','ingrid'],['ヤスミン','yasmine']].map(([name,slug])=>({name,id:slug,image:`./assets/characters/character_${slug}_l.png`}));
const LIVE_CATEGORY_LABELS={ranked:'ランクマッチ',custom:'参加型',tournament:'大会',casual:'カジュアル',training:'トレーニング',avatar_battle:'アバターバトル',other:'その他'};
const STREAMER_CATEGORY_LABELS={pro_gamer:'プロゲーマー',vtuber:'VTuber',game_streamer:'ゲーム配信者'};
const state={data:{characters:CHARACTER_ROSTER,streams:[],upcoming:[],streamers:[]},view:'home',query:'',charFilter:'all',liveCategoryFilter:'all',favorites:JSON.parse(localStorage.getItem('sf6-live-favorites')||'[]')};
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>\\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;'}[c]));
const chars=()=>state.data.characters;const streams=()=>state.data.streams;const charByName=n=>chars().find(c=>c.name===n)||null;const characterSlug=n=>charByName(n)?.id||String(n||'').trim().normalize('NFKC').toLowerCase().replace(/[^\\p{L}\\p{N}]+/gu,'-');
const parseCharacterNames=v=>{const values=Array.isArray(v)?v:String(v??'').split(',');return [...new Set(values.map(x=>String(x??'').trim()).filter(x=>x&&x.toLowerCase()!=='unknown'))];};
const liveCategoryLabel=v=>LIVE_CATEGORY_LABELS[v]||v||'その他';const streamerCategoryLabel=v=>STREAMER_CATEGORY_LABELS[v]||v||'--';const isFav=id=>state.favorites.includes(id);const saveFavs=()=>localStorage.setItem('sf6-live-favorites',JSON.stringify(state.favorites));
function toggleFav(id){state.favorites=isFav(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];saveFavs();render();}
function nav(view){state.view=view;state.charFilter='all';state.liveCategoryFilter='all';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));render();}
function formatJst(value,fallback='--'){const d=new Date(value);if(Number.isNaN(d.getTime()))return fallback;return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(d);}
function filteredUpcoming(){return state.data.upcoming.filter(s=>(state.charFilter==='all'||s.characterNames.some(n=>characterSlug(n)===state.charFilter))&&(!state.query||`${s.streamer} ${s.title} ${s.characterNames.join(' ')}`.toLowerCase().includes(state.query.toLowerCase()))).sort((a,b)=>{const at=Date.parse(a.scheduledStart),bt=Date.parse(b.scheduledStart);if(!Number.isFinite(at)&&!Number.isFinite(bt))return 0;if(!Number.isFinite(at))return 1;if(!Number.isFinite(bt))return -1;return at-bt;});}
function filteredLive(){return streams().filter(s=>s.status==='live'&&(state.charFilter==='all'||s.characterNames.some(n=>characterSlug(n)===state.charFilter))&&(state.liveCategoryFilter==='all'||s.category===state.liveCategoryFilter)&&(!state.query||`${s.streamer} ${s.title} ${s.characterNames.join(' ')}`.toLowerCase().includes(state.query.toLowerCase())));}
function availableLiveCategories(){const order=['ranked','custom','tournament','casual','training','avatar_battle','other'];return [...new Set(streams().filter(s=>s.status==='live').map(s=>s.category||'other'))].sort((a,b)=>(order.indexOf(a)<0?999:order.indexOf(a))-(order.indexOf(b)<0?999:order.indexOf(b)));}
function liveCard(s){const names=s.characterNames.join(' / ');return `<article class="stream-card" data-open="${esc(s.id)}"><div class="thumb" style="background-image:url('${esc(s.thumbnail)}');background-size:cover;background-position:center"><span class="live-pill">● LIVE</span>${names?`<span class="char-badge">${esc(names)}</span>`:''}</div><div class="card-body"><div class="title-row"><strong class="stream-title">${esc(s.title)}</strong><button class="favorite ${isFav(s.streamerId)?'on':''}" data-fav="${esc(s.streamerId)}" aria-label="お気に入り">${isFav(s.streamerId)?'♥':'♡'}</button></div><div class="stream-channel">${esc(s.streamer)}</div><div class="meta">${names?`<span>◉ ${esc(names)}</span>`:''}<span class="live-category">${esc(liveCategoryLabel(s.category))}</span>${s.viewers!=null?`<span>👁 ${Number(s.viewers).toLocaleString()}</span>`:''}</div></div></article>`;}
function upcomingCard(s){const names=s.characterNames.join(' / ');return `<article class="upcoming-card" data-open="${esc(s.id)}"><div class="upcoming-thumb" style="background-image:${s.thumbnail?`linear-gradient(135deg,rgba(20,24,31,.12),rgba(17,21,27,.78)),url('${esc(s.thumbnail)}')`:'linear-gradient(135deg,#252b35,#11151b)'};background-size:cover;background-position:center"><span class="upcoming-time">${esc(formatJst(s.scheduledStart))}</span></div><div class="upcoming-body"><div class="title-row"><strong class="stream-title">${esc(s.title)}</strong><button class="favorite ${isFav(s.streamerId)?'on':''}" data-fav="${esc(s.streamerId)}" aria-label="お気に入り">${isFav(s.streamerId)?'♥':'♡'}</button></div><div class="stream-channel">${esc(s.streamer)}</div><div class="meta">${names?`<span>◉ ${esc(names)}</span>`:''}<span>YouTube</span></div></div></article>`;}
function home(){const live=filteredLive(),selectedCharacter=state.charFilter!=='all'?charByName(state.charFilter):null,selectedCategory=state.liveCategoryFilter!=='all'?liveCategoryLabel(state.liveCategoryFilter):null,categories=availableLiveCategories();return `<section class="section"><div class="section-head"><div><h2>🔴 NOW LIVE</h2><p>${selectedCharacter?`${esc(selectedCharacter.name)} の現在LIVE中の配信`:selectedCategory?`${esc(selectedCategory)} の現在LIVE中の配信`:'いま見られるスト6配信'}</p></div><span class="result-count">${live.length} streams</span></div><div class="filter-row"><button class="chip ${state.liveCategoryFilter==='all'?'active':''}" data-live-category="all">すべて</button>${categories.map(c=>`<button class="chip ${state.liveCategoryFilter===c?'active':''}" data-live-category="${esc(c)}">${esc(liveCategoryLabel(c))}</button>`).join('')}${selectedCharacter?`<button class="chip active" data-clear-char>◉ ${esc(selectedCharacter.name)}</button>`:''}</div><div class="live-grid">${live.length?live.map(liveCard).join(''):'<div class="empty">現在LIVE中の配信はありません。</div>'}</div></section>`;}
function upcomingPage(){const items=filteredUpcoming();return `<section class="section"><div class="section-head"><div><h2>配信予定</h2><p>YouTubeで公開予定になっているSF6 LIVE</p></div><span class="result-count">${items.length} streams</span></div><div class="filter-row"><button class="chip ${state.charFilter==='all'?'active':''}" data-upcoming-char="all">すべて</button>${chars().map(c=>`<button class="chip ${state.charFilter===c.id?'active':''}" data-upcoming-char="${c.id}">${esc(c.name)}</button>`).join('')}</div><div class="upcoming-grid">${items.length?items.map(upcomingCard).join(''):'<div class="empty">該当する配信予定はありません。</div>'}</div></section>`;}
function streamersPage(){const names=[...(state.data.streamers||[])].sort((a,b)=>(Number(b.subscriberCount)||0)-(Number(a.subscriberCount)||0)||String(a.name||'').localeCompare(String(b.name||''),'ja'));const liveChannels=new Set(streams().filter(s=>s.status==='live').map(s=>s.streamerId));return `<section class="section"><div class="section-head"><div><h2>配信者</h2><p>Cloudflare D1に登録されている配信者情報</p></div><span class="result-count">${names.length} streamers</span></div><div class="streamer-grid">${names.map(x=>{const live=liveChannels.has(x.id);return `<article class="streamer-card ${live?'is-live':''}" data-streamer-channel="${esc(x.id)}" data-streamer-url="${esc(x.channelUrl)}"><div class="channel-avatar-wrap">${x.channelThumbnailUrl?`<img class="channel-icon" src="${esc(x.channelThumbnailUrl)}" alt="${esc(x.name)} のYouTubeチャンネルアイコン" loading="lazy" referrerpolicy="no-referrer">`:''}</div><div class="streamer-row"><strong>${esc(x.name)}</strong><button class="favorite ${isFav(x.id)?'on':''}" data-fav="${esc(x.id)}">${isFav(x.id)?'♥':'♡'}</button></div><div class="streamer-stats"><span><b>登録者</b>${x.subscriberCount!=null?Number(x.subscriberCount).toLocaleString():'--'}</span><span><b>カテゴリ</b>${esc(x.streamerCategoryLabel||x.streamerCategory||'--')}</span></div><small>${x.lp!=null?`LP ${esc(x.lp)}`:''}${x.mr!=null?` · MR ${esc(x.mr)}`:''}</small></article>`;}).join('')}</div></section>`;}
function charactersPage(){return `<section class="section"><div class="section-head"><div><h2>キャラクター</h2><p>現在実装されているファイターの公式アート</p></div></div><div class="character-grid">${chars().map(c=>{const count=[...streams(),...state.data.upcoming].filter(s=>s.characterNames.some(n=>characterSlug(n)===c.id)).length;return `<article class="character-card" data-character="${c.id}"><div class="character-art image-art" style="background-image:linear-gradient(180deg,rgba(8,10,15,.02),rgba(8,10,15,.84)),url('${c.image}')"></div><strong>${esc(c.name)}</strong><small>${count} streams</small></article>`}).join('')}</div></section>`;}
function favoritesPage(){const fav=[...streams(),...state.data.upcoming].filter(s=>isFav(s.streamerId));return `<section class="section"><div class="section-head"><div><h2>お気に入り</h2><p>このブラウザだけに保存されます。アカウントは不要です。</p></div></div>${fav.length?`<div class="upcoming-grid">${fav.map(s=>s.status==='upcoming'?upcomingCard(s):liveCard(s)).join('')}</div>`:'<div class="empty">お気に入りの配信者はありません。</div>'}</section>`;}
function simplePage(title,body){return `<section class="section"><div class="page-card"><h2>${title}</h2>${body}</div></section>`;}
function render(){const app=$('#app'),titles={home:'配信中',upcoming:'配信予定',streamers:'配信者',characters:'キャラクター',favorites:'お気に入り',notice:'お知らせ',settings:'設定',help:'使い方'};$('#page-title').textContent=titles[state.view];if(state.view==='home')app.innerHTML=home();else if(state.view==='upcoming')app.innerHTML=upcomingPage();else if(state.view==='streamers')app.innerHTML=streamersPage();else if(state.view==='characters')app.innerHTML=charactersPage();else if(state.view==='favorites')app.innerHTML=favoritesPage();else if(state.view==='notice')app.innerHTML=simplePage('お知らせ','<div class="notice">Cloudflare D1 APIと接続しています。<span>実データ</span></div>');else if(state.view==='settings')app.innerHTML=simplePage('設定','<p>API：<strong>Cloudflare Worker / D1</strong></p><p>お気に入りは localStorage に保存されています。</p><button class="chip" id="clear-favs">お気に入りをすべて削除</button>');else app.innerHTML=simplePage('使い方','<p><strong>NOW LIVE</strong> から現在LIVE中の配信を探せます。</p><p><strong>配信予定</strong> ではYouTubeのupcoming配信を開始時刻順に表示します。</p><p><strong>キャラクター</strong> では公式キャラクターアートから配信を探せます。</p>');bind();}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));document.querySelectorAll('[data-live-category]').forEach(b=>b.onclick=()=>{state.liveCategoryFilter=b.dataset.liveCategory;render();});document.querySelectorAll('[data-clear-live-filter]').forEach(b=>b.onclick=()=>{state.charFilter='all';state.liveCategoryFilter='all';state.view='home';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view==='home'));render();});document.querySelectorAll('[data-upcoming-char]').forEach(b=>b.onclick=()=>{state.charFilter=b.dataset.upcomingChar;state.liveCategoryFilter='all';state.view='upcoming';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view==='upcoming'));render();});document.querySelectorAll('[data-clear-char]').forEach(b=>b.onclick=()=>{state.charFilter='all';render();});document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav);});document.querySelectorAll('[data-open]').forEach(card=>card.onclick=()=>openStream(card.dataset.open));document.querySelectorAll('[data-streamer-channel]').forEach(card=>card.onclick=e=>{if(e.target.closest('[data-fav]'))return;const url=card.dataset.streamerUrl;if(url)window.open(url,'_blank','noopener');});const clear=$('#clear-favs');if(clear)clear.onclick=()=>{state.favorites=[];saveFavs();render();};document.querySelectorAll('.character-card').forEach(card=>card.onclick=()=>{state.charFilter=card.dataset.character;state.liveCategoryFilter='all';state.view='home';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view==='home'));render();});}
function openStream(id){const s=[...streams(),...state.data.upcoming].find(x=>x.id===id);if(s)window.open(s.youtubeUrl,'_blank','noopener');}
function mapVideo(v){const characterNames=parseCharacterNames(v.main_characters??v.main_character);return {id:v.video_id,streamerId:v.channel_id,characterNames,streamer:v.sf6_player_name||v.channel_title||v.channel_id,channelThumbnailUrl:v.channel_thumbnail_url||'',status:v.status,viewers:v.concurrent_viewers,title:v.title||'',youtubeUrl:`https://www.youtube.com/watch?v=${v.video_id}`,thumbnail:v.thumbnail_url||`https://i.ytimg.com/vi/${v.video_id}/hqdefault.jpg`,lp:v.lp,mr:v.mr,category:v.category||'other',scheduledStart:v.scheduled_start_time,actualStart:v.actual_start_time,actualEnd:v.actual_end_time};}
function mapStreamer(s){return {id:s.channel_id,name:s.sf6_player_name||s.channel_title||s.channel_id,channelThumbnailUrl:s.channel_thumbnail_url||'',channelUrl:`https://www.youtube.com/channel/${encodeURIComponent(s.channel_id)}`,subscriberCount:s.subscriber_count,lp:s.lp,mr:s.mr,streamerCategory:s.streamer_category,streamerCategoryLabel:streamerCategoryLabel(s.streamer_category)};}
async function fetchJson(url){const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
async function fetchVideos(status,limit=200){return fetchJson(`${API_BASE}/api/videos?status=${encodeURIComponent(status)}&limit=${limit}`);}
async function fetchStreamers(){try{const payload=await fetchJson(`${API_BASE}/api/streamers?limit=1000`);state.data.streamers=(payload.items||[]).map(mapStreamer);}catch(e){console.error('streamers fetch failed',e);state.data.streamers=[];}}
async function loadApiData(){const [allPayload,upcomingPayload]=await Promise.all([fetchVideos('all'),fetchVideos('upcoming')]);await fetchStreamers();state.data.streams=(allPayload.items||[]).map(mapVideo).filter(v=>v.status==='live');state.data.upcoming=(upcomingPayload.items||[]).map(mapVideo).filter(v=>v.status==='upcoming');}
document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>nav(n.dataset.view));
const search=$('#search');if(search)search.oninput=()=>{state.query=search.value;render();};
loadApiData().then(render).catch(e=>{console.error(e);render();});
